### ISSUE TITLE
Fix implementation of `ChargebyteChargingStation.get_max_charge_current`

### ISSUE THREAD

**Issue by giselaortt** [securityinmobility/dc-charging-station#12]

**Comment by giselaortt** [comment]
Can you provide more information? I dont know what you are talking about.

**Comment by M4GNV5** [comment]
currently there are three functions:
- `enable_pullup_resistor`
- `disable_pullup_resistor`
- `get_voltage_of_proximity_signal`

These together can be used in the high level `CharbyteChargingStation` to measure the resistance of the PP resistor.
The pullup resistor forms together with the PP resistor a voltage dividor between the pullup voltage and PE.

See this site for a basic explanation how it works and how to calculate the PE resistor https://ohmslawcalculator.com/voltage-divider-calculator

**Comment by M4GNV5** [comment]
adjusted title. The function currently does not return the expected type (see base class)
