### ISSUE TITLE
Correctly initialize charging station communication in CharbyteChargingStation

### ISSUE THREAD

**Issue by giselaortt** [securityinmobility/dc-charging-station#17]
- [ ] optionally set PP resistor (should be configured via __init__)
- [x] enable PP pullup
- [ ] set constant 12V output (or PWM)
- [x] wait for first voltage drop using `ChargebyteBoard.get_cp`
- [x] set 5% PWM
- [x] check for second voltage drop

**Comment by giselaortt** [comment]
**_wait for first voltage drop using ChargebyteBoard.get_cp:_**  cant i simple use self.get_state? i think that is why we have this function at all.

**Comment by M4GNV5** [comment]
yes, you can also use the abstraction, no problem :+1:
