### ISSUE TITLE
chargebyte: When both packet response and regular message is sent they might be mixed up resulting in the regular message used as packet response (probably broken)

### ISSUE THREAD

**Issue by M4GNV5** [securityinmobility/dc-charging-station#8]
How it is normally solved:
- have one thread reading packets
- if its a regular message: decode and store data
- if its a response to a request: store it into a Queue
- when sending a request that requires a reponse: take it out of the queue

python queue: https://docs.python.org/3/library/queue.html#queue.Queue

**Comment by giselaortt** [comment]
the problem with this queue is that the answer might not be on the top of the queue. and i cannot take an answer from the second position or the third. is a list not suited for this use case?

**Comment by giselaortt** [comment]
the only service that is not a response is the 0xC0 , a cyclic message. when the read_response thread reads a cyclic message, what should happen? should we have a queue of messages for the user to take from, or should there be an observer that sends this message to the user? i dont see how to make the message go to the user from here.
